# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID:      "tmtrackdev01"
  _REGION:          "europe-west1"
  _COMPOSER_BUCKET: "europe-west1-dataops-pfe-composer-env-bucket"
  _DATA_BUCKET:     "tmt-storage-01"
  _TF_VAR_FILE:     "Terraform/terraform.tfvars"
  _IMAGE:           "gcr.io/$_PROJECT_ID/dataloader-image:latest"

steps:
  # 0) Adoucir le warning Git
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Git Config"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git config --global init.defaultBranch main

  # 1) Init Terraform + téléchargement des providers
  - name: "hashicorp/terraform:light"
    id: "Terraform Init"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform init -var-file=$_TF_VAR_FILE

  # 2) Validate (certifie que la config est correcte)
  - name: "hashicorp/terraform:light"
    id: "Terraform Validate"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform validate

  # 3) Apply Terraform
  - name: "hashicorp/terraform:light"
    id: "Terraform Apply"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform apply -auto-approve -var-file=$_TF_VAR_FILE

  # 4) Build + Push Docker pour Cloud Run
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Dataloader"
    args: ["build","-t","$_IMAGE","-f","Dataloader/Dockerfile","."]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Dataloader"
    args: ["push","$_IMAGE"]

  # 5) Copier le CSV vers Storage
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Upload CSV"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil cp RAPToR_Azure_Resources_Inventory_02-03-2024.csv gs://$_DATA_BUCKET/

  # 6) Synchroniser les DAGs dans Composer
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Sync DAGs"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil -m rsync -r Dags gs://$_COMPOSER_BUCKET/dags

  # 7) Déployer sur Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Cloud Run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy dataloader-service \
          --image "$_IMAGE" \
          --region "$_REGION" \
          --platform managed \
          --allow-unauthenticated
