# cloudbuild.yaml

options:
  # Envoie uniquement les logs vers Cloud Logging, pas besoin de bucket GCS
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID:      "tmtrackdev01"
  _REGION:          "europe-west1"
  _COMPOSER_BUCKET: "europe-west1-dataops-pfe-composer-env-bucket"
  _DATA_BUCKET:     "tmt-storage-01"
  _TF_VAR_FILE:     "Terraform/terraform.tfvars"
  _IMAGE:           "gcr.io/$_PROJECT_ID/dataloader-image:latest"

steps:
  # 0) Quiet Git warning by defaulting branch to main
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Git Config"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git config --global init.defaultBranch main

  # 1) Validate your Terraform code
  - name: "hashicorp/terraform:light"
    id: "Terraform Validate"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform validate

  # 2) Init & apply Terraform
  - name: "hashicorp/terraform:light"
    id: "Terraform Apply"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform init -var-file=$_TF_VAR_FILE
        terraform apply -auto-approve

  # 3) Build Docker image for Cloud Run
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Dataloader"
    args:
      - "build"
      - "-t"
      - "$_IMAGE"
      - "-f"
      - "Dataloader/Dockerfile"
      - "."

  # 4) Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Dataloader"
    args:
      - "push"
      - "$_IMAGE"

  # 5) Upload inventory CSV to Cloud Storage
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Upload CSV"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil cp RAPToR_Azure_Resources_Inventory_02-03-2024.csv gs://$_DATA_BUCKET/

  # 6) Sync DAGs to Cloud Composer bucket
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Sync DAGs"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil -m rsync -r Dags gs://$_COMPOSER_BUCKET/dags

  # 7) Deploy or update the Cloud Run service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Cloud Run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy dataloader-service \
          --image "$_IMAGE" \
          --region "$_REGION" \
          --platform managed \
          --allow-unauthenticated
